### ISSUE TITLE
KaiGenGothicCN-Regular-Italic.ttf not found

### ISSUE THREAD

**Issue by Robin7Ma** [chloerei/asciidoctor-pdf-cjk#1]
Rei, 你好!

我在使用中发现ruby下asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/data/fonts/目录为空, 因此我从[KaiGen Gothic](https://github.com/akiratw/kaigen-gothic)下载了所有字体, 但运行时仍提示

```
asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/data/fonts/KaiGenGothicCN-Regular-Italic.ttf not found
```

请问这些斜体是从哪里取得的?

我运行的命令是:

```
asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicCN config.adoc
```

谢谢!

**Comment by chloerei** [comment]
这个问题应该提交到 https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic

asciidoctor-pdf-cjk-kai_gen_gothic 安装完之后有个命令下载所有字体：

```
asciidoctor-pdf-cjk-kai_gen_gothic-install
```

因为 gem 的体积不能太大，所以我把字体放在 https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/tag/v0.1.0-fonts ，然后通过脚本下载放到 gem 的安装目录。

斜体是用 fontforge 转换的，脚本在这里 https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/blob/master/bin/convert_italic.pe

**Comment by Robin7Ma** [comment]
好的, 非常感谢. 另外我使用的是asciidoctor-maven-plugin, 并将asciidoctor-pdf-cjk 和 asciidoctor-pdf-cjk-kai_gen_gothic 转换为jar, 使用JRuby运行, 但运行时提示 

```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2:process-asciidoc (generate-docs) on project rest-notes-spring-data-rest: Execution generate-docs of goal org. asciidoctor:asciidoctor-maven-plugin:1.5.2:process-asciidoc failed: (SyntaxError) (RegexpError) invalid character property name <Han>: /(?<!\p{Space})[\p{Han}\p{Hiragana}\p{Katakana}]/ -> [Help 1]
```

请问您是否了解这可能是哪里使用有问题? 谢谢.

**Comment by chloerei** [comment]
似乎是正则表达式不兼容，用的 JRuby 版本是多少？据说 JRuby 9k 兼容 CRuby 2.2，这个 gem 是基于 2.2 写的。

**Comment by Robin7Ma** [comment]
是从官方的例子中Copy的, JRuby使用的是 1.7.x 版本, 我试一下9.x 版本先.

**Comment by Robin7Ma** [comment]
果然是版本问题, 现在似乎asciidoctor-pdf-cjk 使用没问题了, 刚才下载字体出现SSL错误, 不是太懂, 求指导, 谢谢!!

``` dos
C:\Users\m>asciidoctor-pdf-cjk-kai_gen_gothic-install
[1/20] Downloading KaiGenGothicCN-Bold-Italic.ttf
C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:318:in `open_http'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:716:in `open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:34:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:34:in `block (3 levels) in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:33:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:33:in `block (2 levels) in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:31:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:31:in `each_with_index'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:31:in `block in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:30:in `chdir'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.0/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:30:in `<top (required)>'
        from C:/Ruby22-x64/bin/asciidoctor-pdf-cjk-kai_gen_gothic-install:23:in `load'
        from C:/Ruby22-x64/bin/asciidoctor-pdf-cjk-kai_gen_gothic-install:23:in `<main>'
```

**Comment by chloerei** [comment]
看起来是 openssl 证书的问题，但我不确定 Windows 下如何解决，可以参考

https://ruby-china.org/topics/24840

**Comment by Robin7Ma** [comment]
最后手动下载了所有的字体，确实解决很中文的问题，非常感谢！
